### PR TITLE
removed ds store and added gitignore :)

### PR DESCRIPTION
**Pull request by loctauxphilippe**

### CODE REVIEW

**Comment by TheAndroidMaster** [comment]
I have... no clue what this does but thanks... I guess :+1:

**Comment by loctauxphilippe** [comment]
with the gitignore, you add every file that you don't want to add to the repo like .DS_Store and other stuff :)

**Comment by TheAndroidMaster** [comment]
How would you exclude all .png files from the repo? If I read the docs right, would you would just add a line with `*.png` in it? (I want to check first, in case I mess something up)

**Comment by loctauxphilippe** [comment]
Yes exactly!

--
Philippe Loctaux

**Pull request merged**
